<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('payslips', function (Blueprint $table) {
            $table->id();

            /*
             * EMPLOYEE PAYROLL RESULT
             *
             * One finalized payroll result
             * should have at most one payslip.
             */
            $table->foreignId('payroll_employee_result_id')
                ->constrained('payroll_employee_results')
                ->cascadeOnUpdate()
                ->restrictOnDelete();

            /*
             * EMPLOYEE
             *
             * Denormalized reference for easier
             * ESS payslip queries.
             */
            $table->foreignId('employee_id')
                ->constrained('employees')
                ->cascadeOnUpdate()
                ->restrictOnDelete();

            /*
             * PAYSLIP NUMBER
             *
             * Example:
             *
             * PS-2026-09-000001
             *
             * Actual numbering format will be
             * generated by the application.
             */
            $table->string('payslip_number', 50)
                ->unique();

            /*
             * STATUS
             *
             * Suggested values:
             *
             * draft
             * published
             * revoked
             */
            $table->string('status', 30)
                ->default('draft');

            /*
             * PUBLICATION
             *
             * Once published, employee can see
             * the payslip through ESS.
             */
            $table->timestamp('published_at')
                ->nullable();

            $table->foreignId('published_by_user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete()
                ->cascadeOnUpdate();

            /*
             * OPTIONAL GENERATED PDF
             *
             * PDF can be generated when publishing
             * or on demand.
             *
             * Store in private storage.
             */
            $table->string('pdf_path', 500)
                ->nullable();

            /*
             * REVOCATION
             *
             * Useful if a payslip was accidentally
             * published and needs to be hidden.
             *
             * Revocation does NOT delete or alter
             * the finalized payroll result.
             */
            $table->timestamp('revoked_at')
                ->nullable();

            $table->foreignId('revoked_by_user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete()
                ->cascadeOnUpdate();

            $table->string('revocation_reason', 255)
                ->nullable();

            /*
             * OPTIONAL REMARKS
             */
            $table->text('remarks')
                ->nullable();

            $table->timestamps();

            /*
             * ONE PAYSLIP PER EMPLOYEE PAYROLL RESULT
             */
            $table->unique(
                'payroll_employee_result_id',
                'uq_payslips_payroll_result'
            );

            /*
             * INDEXES
             */
            $table->index(
                ['employee_id', 'status', 'published_at'],
                'idx_payslips_employee_status'
            );

            $table->index(
                ['status', 'published_at'],
                'idx_payslips_status_published'
            );
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payslips');
    }
};